// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icryeaibetgjgecgxjjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcnllYWliZXRnamdlY2d4ampkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzE1OTQsImV4cCI6MjA2NTU0NzU5NH0.ENNMWd1d_lxOrSjeC-GB4ewJX5e6LasYsbug6IjLRRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
